[package]
name = "arcmis-tools"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rig = "0.42.0"
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["process", "macros", "rt-multi-thread"] }
tracing.workspace = true

[dev-dependencies]
cucumber.workspace = true
tokio.workspace = true

[features]
cucumber-tests = []

[[test]]
name = "cucumber"
harness = false
required-features = ["cucumber-tests"]
