[package]
name = "ARCMiS-agents"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "agents"

[dependencies]
tools = { package = "ARCMiS-tools", path = "../tools" }
rig = "0.42.0"
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio = { workspace = true, features = ["process", "macros"] }
tracing.workspace = true
bon = "3.10.1"

[dev-dependencies]
cucumber.workspace = true
tokio.workspace = true

[features]
cucumber-tests = []

[[test]]
name = "cucumber"
harness = false
required-features = ["cucumber-tests"]
