[package]
name = "ulidgen"
version = "0.1.0"
edition = "2021"
description = "Generate ULIDs (Universally Unique Lexicographically Sortable Identifiers)"
license = "Unlicense"

[lib]
name = "ulidgen_r"
path = "src/lib.rs"

[[bin]]
name = "ulidgen"
path = "src/main.rs"

[dependencies]
getrandom = { version = "0.2", features = ["std"] }

[workspace]
