[package]
name = "ulidgen"
version = "0.1.0"
edition = "2021"
description = "Generate ULIDs (Universally Unique Lexicographically Sortable Identifiers)"
license = "Unlicense"

[lib]
name = "ulidgen"
path = "src/lib.rs"

[[bin]]
name = "ulidgen"
path = "src/main.rs"

[profile.release]
opt-level = 3

[workspace]
